name: Tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install OS Dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get -y install graphviz
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install graphviz
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install graphviz
          fi
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -U importlib-metadata>=1.7.0
          pip install -U -r requirements.txt
          pip install -U -r requirements_dev.txt
          pip install ipython
          python setup.py install
      - name: Test with pytest
        run: |
          pytest tests --cov=supervised/
    continue-on-error: true